server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # 路由刷新404修复
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 测试环境接口代理
    location /stage-api/ {
        proxy_pass http://backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 生产环境接口代理
    location /prod-api/ {
        proxy_pass http://backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
